# clean all files generated by test and gencoe

if (test-path *.o) {rm -force *.o}
if (test-path *.out) {rm -force *.out}
if (test-path *.code) {rm -force *.code}
if (test-path *.bin) {rm -force *.bin}
if (test-path *.coe) {rm -force *.coe}
if (test-path *.data) {rm -force *.data}
if (test-path *.dat) {rm -force *.dat}
if (test-path *.result) {rm -force *.result}
cd ../src
if (test-path transcript) {rm -force transcript}
if (test-path work) {rm -force -recurse work}
if (test-path *wlf*) {rm -force *wlf*}
if (test-path CPU_sim.vhd) {rm -force CPU_sim.vhd}
if (test-path memory.dat) {rm -force memory.dat}
if (test-path *.in) {rm -force *.in}
if (test-path *.debug) {rm -force *.debug}
if (test-path *.output) {rm -force *.output}
cd ../test
